[2024-12-14 21:01:21,736] {scheduler_job.py:181} INFO - Started process (PID=11588) to work on /opt/airflow/dags/dag_producer.py
[2024-12-14 21:01:21,737] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/dag_producer.py for tasks to queue
[2024-12-14 21:01:21,738] {logging_mixin.py:104} INFO - [2024-12-14 21:01:21,738] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_producer.py
[2024-12-14 21:01:21,758] {logging_mixin.py:104} INFO - [2024-12-14 21:01:21,754] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_producer.py", line 5, in <module>
    from airflow.datasets import Dataset
ModuleNotFoundError: No module named 'airflow.datasets'
[2024-12-14 21:01:21,764] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_producer.py
[2024-12-14 21:01:21,780] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/dag_producer.py took 0.047 seconds
