[2024-12-14 21:01:22,801] {scheduler_job.py:181} INFO - Started process (PID=11597) to work on /opt/airflow/dags/dag_jinja_use.py
[2024-12-14 21:01:22,803] {scheduler_job.py:632} INFO - Processing file /opt/airflow/dags/dag_jinja_use.py for tasks to queue
[2024-12-14 21:01:22,805] {logging_mixin.py:104} INFO - [2024-12-14 21:01:22,805] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_jinja_use.py
[2024-12-14 21:01:22,853] {logging_mixin.py:104} INFO - [2024-12-14 21:01:22,848] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_jinja_use.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_jinja_use.py", line 11, in <module>
    param_val = get_param_value(aod="{{ ds }}")
TypeError: get_param_value() got an unexpected keyword argument 'aod'
[2024-12-14 21:01:22,857] {scheduler_job.py:644} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_jinja_use.py
[2024-12-14 21:01:22,873] {scheduler_job.py:189} INFO - Processing /opt/airflow/dags/dag_jinja_use.py took 0.075 seconds
